<?php
/**
 * BLOG POST REGISTRY
 * ------------------
 * To publish a new blog post, add a new entry at the TOP of this array.
 * 'image' path is relative to the website root folder.
 * 'url'   path is relative to the website root folder.
 * Posts are displayed newest-first; the homepage shows the top 3.
 */
$blogPosts = [
    [
        'title'    => 'Hair Transplant Cost vs Results: What Every Patient Should Realistically Expect',
        'desc'     => 'Understand how hair transplant pricing works, what cheap clinics cut corners on, and what realistic density results look like after surgery.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht-success-2.png',
        'url'      => 'blog/hair-transplant-cost-vs-results-patient-expectations.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant Recovery Timeline: What Patients Feel Week by Week',
        'desc'     => 'A detailed week-by-week recovery guide after hair transplant — from day-1 swelling to month-12 final results.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht-success-1.png',
        'url'      => 'blog/hair-transplant-recovery-timeline-week-by-week.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'What a Patient Experiences During Hair Transplant Surgery: Step-by-Step',
        'desc'     => 'A complete step-by-step walkthrough of what happens on hair transplant day — from arrival to going home.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/tech-procedure.png',
        'url'      => 'blog/hair-transplant-surgery-step-by-step-patient-experience.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Why Some Patients Don\'t Get Desired Results After Hair Transplant',
        'desc'     => 'Explore the real reasons behind poor hair transplant outcomes — from clinic selection to post-op care — and how to avoid them.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/indian-ht-result-2.png',
        'url'      => 'blog/why-patients-dont-get-desired-results-hair-transplant.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant Gone Wrong? Common Patient Mistakes to Avoid',
        'desc'     => 'Discover the most common mistakes patients make before and after hair transplant surgery — and how to protect your results.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_success_real_1.png',
        'url'      => 'blog/hair-transplant-gone-wrong-common-patient-mistakes.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'What Happens If You Don\'t Have Enough Donor Hair? Patient Options',
        'desc'     => 'Learn what options exist when donor hair supply is limited — from body hair transplant to SMP and PRP conditioning.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_crown_real.png',
        'url'      => 'blog/not-enough-donor-hair-transplant-options.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Can Patients with Diabetes or BP Undergo Hair Transplant? Expert Insights',
        'desc'     => 'Find out how diabetes and high blood pressure affect hair transplant eligibility, HbA1c thresholds, and pre-op clearance.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_hairline_real.png',
        'url'      => 'blog/hair-transplant-diabetes-blood-pressure-patients.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant for Different Age Groups: What Patients Should Know',
        'desc'     => 'How age affects hair transplant candidacy, results, and planning — from under 25 to 50+ patients.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_gallery_extra_1.png',
        'url'      => 'blog/hair-transplant-different-age-groups-what-to-know.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Who Is an Ideal Candidate for Hair Transplant? Age, Hair Loss & Health',
        'desc'     => 'A detailed look at what makes someone an ideal hair transplant candidate — donor density, Norwood scale, age, and health factors.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/indian-ht-result-1.png',
        'url'      => 'blog/ideal-candidate-hair-transplant-age-hair-loss-health.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Is Hair Transplant Right for You? A Complete Patient Eligibility Guide',
        'desc'     => 'Not everyone is a candidate. This guide covers all eligibility criteria for hair transplant — medical, physical, and psychological.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_success_real.png',
        'url'      => 'blog/is-hair-transplant-right-for-you-eligibility-guide.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Fall & Hair Loss Prevention: The Ultimate Guide',
        'desc'     => 'Discover the most effective strategies to stop hair fall and maintain thick, healthy hair naturally.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-fall-prevention-featured.png',
        'url'      => 'blog/hair-fall-and-hair-loss-prevention.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Hair Growth Tips & Methods: How to Grow Hair Faster',
        'desc'     => 'The best hair growth tips and methods to accelerate hair growth naturally through scalp health, diet, and clinical treatments.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-growth-tips-featured.png',
        'url'      => 'blog/hair-growth-tips-and-methods.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Best Oils for Hair Growth: A Comprehensive Guide',
        'desc'     => 'From Rosemary to Castor oil — explore the best natural oils for thicker, longer hair and how to use them effectively.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/best-hair-oils-featured.png',
        'url'      => 'blog/best-hair-oils-for-growth-benefits.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Hair Thickness & Hair Density Improvement: The Complete Guide',
        'desc'     => 'Learn how to increase hair thickness and improve hair density naturally with the best tips, treatments, and products.',
        'category' => 'Hair Volume',
        'image'    => 'images/blog/hair-thickness-density-featured.png',
        'url'      => 'blog/hair-thickness-and-hair-density-improvement.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Vitamins & Nutrition for Healthy Hair: The Ultimate Diet Guide',
        'desc'     => 'Which vitamins and nutrients are essential for healthy hair? Discover the best foods and supplements to stop hair loss.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/vitamins-for-hair-featured.png',
        'url'      => 'blog/vitamins-nutrition-healthy-hair.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Dandruff & Scalp Problems: Causes and Effective Treatments',
        'desc'     => 'Struggling with flakes or an itchy scalp? Learn about causes of dandruff and the most effective clinical and natural treatments.',
        'category' => 'Scalp Health',
        'image'    => 'images/blog/dandruff-scalp-problems-featured.png',
        'url'      => 'blog/dandruff-scalp-problems-treatment.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Understanding Hair Transplant: Myths vs Facts',
        'desc'     => 'We bust common myths and highlight essential facts you need to know before booking your hair transplant procedure.',
        'category' => 'Hair Care',
        'image'    => 'images/hair-transplant-original.jpg',
        'url'      => 'blog/understanding-hair-transplant-myths-vs-facts.php',
        'date'     => '2026-02-25',
    ],
    [
        'title'    => 'Benefits of HydraFacial: How It Transforms Your Skin',
        'desc'     => 'How HydraFacial deep-cleans, exfoliates, and hydrates for an instant radiant glow with zero downtime.',
        'category' => 'Skin Care',
        'image'    => 'images/hydrafacial.jpg',
        'url'      => 'blog/benefits-of-hydrafacial-how-it-transforms-your-skin.php',
        'date'     => '2026-02-18',
    ],
    [
        'title'    => 'Everything You Need to Know About Botox and Fillers',
        'desc'     => 'The complete guide to anti-ageing injectables — differences between Botox and dermal fillers and how to choose the best treatment.',
        'category' => 'Anti-Ageing',
        'image'    => 'images/botox.jpg',
        'url'      => 'blog/everything-you-need-to-know-about-botox-and-fillers.php',
        'date'     => '2026-02-12',
    ],
    [
        'title'    => 'Is Laser Hair Removal Permanent? Expert Perspective',
        'desc'     => 'Our experts explain how laser hair removal technology works, what results to expect, and why it\'s the best choice for smooth skin.',
        'category' => 'Laser',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/is-laser-hair-removal-permanent-expert-perspective.php',
        'date'     => '2026-02-05',
    ],
    [
        'title'    => 'PRP Hair Treatment: The Natural Way to Regrow Your Hair',
        'desc'     => 'How Platelet-Rich Plasma therapy uses your own blood to stimulate hair growth and thickening — naturally.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/prp-hair-treatment-natural-way-to-regrow-hair.php',
        'date'     => '2026-01-21',
    ],
    [
        'title'    => 'Chemical Peels: Finding the Right Depth for Your Skin Type',
        'desc'     => 'A complete guide to chemical peels — from light to deep — and which treatment is best for your specific skin concerns.',
        'category' => 'Skin Care',
        'image'    => 'images/service-skin.png',
        'url'      => 'blog/chemical-peels-finding-the-right-depth-for-your-skin-type.php',
        'date'     => '2026-01-08',
    ],
];
