<?php
/**
 * BLOG POST REGISTRY
 * ------------------
 * To publish a new blog post, add a new entry at the TOP of this array.
 * 'image' path is relative to the website root folder.
 * 'url'   path is relative to the website root folder.
 * Posts are displayed newest-first; the homepage shows the top 3.
 */
$blogPosts = [
    [
        'title'    => 'Can I Use Rosemary Water on My Hair Everyday? Expert Answer',
        'desc'     => 'Can you use rosemary water on your hair every day? Learn the safe frequency, benefits, side effects of overuse, and expert tips from DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/can-i-use-rosemary-water-on-my-hair-everyday.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'Can We Apply Aloe Vera Gel on Hair? Complete Expert Guide',
        'desc'     => 'Can you apply aloe vera gel on hair? Yes! Learn the benefits, how to extract and apply fresh aloe vera, best hair masks, and expert tips by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/can-we-apply-aloe-vera-gel-on-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Apply Curd on Hair: Benefits, Methods & Expert Tips',
        'desc'     => 'Learn how to apply curd on hair for dandruff, dryness, frizz, and hair fall. Step-by-step methods, best curd hair masks, and expert tips by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-apply-curd-on-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Apply Egg on Hair: Step-by-Step Guide',
        'desc'     => 'Learn how to apply egg on hair the right way. Step-by-step guide covering egg masks for every hair type, application tips, washing methods, and precautions.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-apply-egg-on-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Apply Onion Juice on Hair: Step-by-Step Guide for Hair Growth',
        'desc'     => 'Learn exactly how to apply onion juice on hair for maximum hair growth. Step-by-step method, preparation tips, how to reduce smell, and precautions — expert guide by DenceSpot Clinic.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-apply-onion-juice-on-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Amla for Hair Growth: Complete Expert Guide',
        'desc'     => 'Learn how to use amla for hair growth — fresh amla, amla powder, amla oil, and DIY amla hair masks. Expert guide by DenceSpot Clinic Gurgaon for thicker, stronger hair.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-amla-for-hair-growth.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Egg for Hair: Benefits, Masks, and Expert Tips',
        'desc'     => 'Discover how to use egg for hair growth, thickness, and repair. Expert guide covering egg masks, benefits for different hair problems, smell removal tips, and results timeline.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-egg-for-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Methi (Fenugreek) for Hair Growth: Complete Guide',
        'desc'     => 'Learn how to use methi (fenugreek) for hair growth — methi paste, methi hair masks, methi water rinse, and methi oil. Expert guide by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-methi-for-hair-growth.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Onion Juice for Hair Growth, Dandruff, and Thickness',
        'desc'     => 'Discover how to use onion juice for hair growth, dandruff control, and thickness. Includes recipes with coconut oil, honey, and aloe vera — plus scientific evidence and results timeline.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-onion-juice-for-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Rice Water for Hair: Complete Guide',
        'desc'     => 'Learn how to use rice water for hair growth, strength, and shine. Discover soaking, boiling, and fermented methods with expert tips from DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-rice-water-for-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Use Rosemary Water for Hair Growth: Complete Guide',
        'desc'     => 'Learn how to use rosemary water for hair growth with 3 preparation methods and expert application techniques. Science-backed guide from DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-use-rosemary-water-for-hair.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'Does Keratin Treatment Damage Hair? The Truth Revealed',
        'desc'     => 'Does keratin treatment damage hair? Learn the truth about keratin side effects, formaldehyde risks, long-term impact on hair health, and safer alternatives.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/does-keratin-treatment-damage-hair-truth-revealed.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Does Laser Hair Removal Permanently Remove Hair? Science Explained',
        'desc'     => 'Does laser hair removal permanently remove hair? Learn the FDA classification, expected reduction percentages, factors affecting results, and how maintenance sessions work. Expert guide by DenceSpot Clinic Gurgaon.',
        'category' => 'Laser',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/does-laser-hair-removal-permanently-remove-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How Much Does Laser Hair Removal Cost in India? Price Guide 2026',
        'desc'     => 'Complete laser hair removal cost guide for India in 2026. See per-session pricing by body area, factors affecting cost, comparison with waxing, and how to choose the right clinic in Gurgaon.',
        'category' => 'Laser',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-much-does-laser-hair-removal-cost.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Apply Hair Mask: Step-by-Step Application Guide',
        'desc'     => 'Master the correct technique for applying hair mask with our detailed step-by-step guide. Learn application tips, timing, and methods for maximum results.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-apply-hair-mask.png',
        'url'      => 'blog/how-to-apply-hair-mask-step-by-step.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Do Hair Spa at Home: Step-by-Step DIY Guide',
        'desc'     => 'Learn how to do a professional-quality hair spa at home with simple ingredients. Step-by-step guide with tips for deep conditioning, scalp massage, and steam treatment.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/how-to-do-hair-spa-at-home-step-by-step.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Get Rid of Frizzy Hair Permanently',
        'desc'     => 'Expert guide on how to get rid of frizzy hair permanently. Discover home remedies, anti-frizz routines, and clinical treatments for smooth, frizz-free hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-get-rid-of-frizzy-hair-permanently.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Keep Hair Healthy: Expert Tips for Strong Hair',
        'desc'     => 'Discover expert-backed tips on how to keep hair healthy. Learn about nutrition, scalp care, product selection, and lifestyle habits for naturally strong, shiny hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-keep-hair-healthy.png',
        'url'      => 'blog/how-to-keep-hair-healthy-expert-tips.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Make Curly Hair at Home Without Heat',
        'desc'     => 'Learn how to make curly hair at home naturally without heat tools. Step-by-step guide with DIY methods, products, and tips for perfect curls.',
        'category' => 'Hair Styling',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-make-curly-hair-at-home.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Make Hair Silky, Smooth & Shiny Naturally',
        'desc'     => 'Learn how to make hair silky and smooth naturally at home. Expert tips on home remedies, diet, and clinical treatments for permanently silky hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-make-hair-silky-smooth-naturally.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Moisturize Dry Hair: Hydration Tips That Work',
        'desc'     => 'Learn how to moisturize dry hair with proven hydration techniques. Discover the best oils, masks, and daily habits to restore moisture and softness to your hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-moisturize-dry-hair.png',
        'url'      => 'blog/how-to-moisturize-dry-hair-hydration-tips.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Facial Hair at Home: Safe DIY Methods',
        'desc'     => 'Learn how to remove facial hair at home safely using threading, waxing kits, turmeric masks, sugaring, and dermaplaning tools. Expert-approved DIY methods by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-facial-hair-at-home.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Facial Hair Naturally: Home Remedies That Work',
        'desc'     => 'Learn how to remove facial hair naturally with turmeric, gram flour, papaya, sugar wax, and more. Safe home remedies by DenceSpot Clinic Gurgaon.',
        'category' => 'Natural Remedies',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-facial-hair-naturally.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Facial Hair Permanently: Laser & Clinical Options',
        'desc'     => 'Learn how to remove facial hair permanently with laser hair removal, electrolysis, and IPL. Expert guide on permanent facial hair removal options, candidacy, session requirements, and aftercare by DenceSpot Clinic Gurgaon.',
        'category' => 'Laser',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-facial-hair-permanently.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Facial Hair: Complete Methods Guide',
        'desc'     => 'Comprehensive guide on how to remove facial hair using threading, waxing, shaving, laser, electrolysis, and natural remedies. Expert advice from DenceSpot Clinic Gurgaon for safe and effective facial hair removal.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-facial-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Hair from Private Parts Safely: Complete Guide',
        'desc'     => 'Learn how to remove hair from private parts safely with expert-approved methods. Discover trimming, shaving, waxing, laser hair removal, and depilatory creams for intimate area hair removal with hygiene tips.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-hair-from-private-parts.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Split Ends from Hair: Prevention & Treatment',
        'desc'     => 'Learn how to remove split ends from hair and prevent them from coming back. Discover trimming techniques, protective treatments, and daily habits for split-end-free hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-remove-split-ends.png',
        'url'      => 'blog/how-to-remove-split-ends-from-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Underarm Hair: Best Methods for Smooth Underarms',
        'desc'     => 'Complete guide on how to remove underarm hair safely. Compare shaving, waxing, laser hair removal, epilating, and depilatory creams. Expert tips for dark underarms, ingrown hairs, and irritation by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-underarm-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Upper Lip Hair at Home: Easy DIY Methods',
        'desc'     => 'Learn how to remove upper lip hair at home using wax strips, turmeric paste, sugar wax, threading, facial razors, and IPL devices. Safe DIY methods by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-upper-lip-hair-at-home.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Upper Lip Hair: Best Methods Compared',
        'desc'     => 'Discover the best methods to remove upper lip hair safely and effectively. Expert comparison of threading, waxing, laser, bleaching, depilatory creams, and dermaplaning. Professional guidance by DenceSpot Clinic Gurgaon.',
        'category' => 'Hair Removal',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-remove-upper-lip-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Repair Damaged Hair: Restoration Tips That Work',
        'desc'     => 'Discover how to repair damaged hair with expert restoration tips. Learn about protein treatments, deep conditioning, and lifestyle changes to restore your hair health.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-repair-damaged-hair.png',
        'url'      => 'blog/how-to-repair-damaged-hair-restoration-tips.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Shave Pubic Hair for Men: Safe Step-by-Step Guide',
        'desc'     => 'Learn how to shave pubic hair for men safely. Expert step-by-step guide covering trimming, shaving technique, aftercare, preventing razor bumps and ingrown hairs, and alternatives like laser hair removal.',
        'category' => 'Grooming',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/how-to-shave-pubic-hair-for-men.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Straighten Hair Naturally at Home',
        'desc'     => 'Learn how to straighten hair naturally at home without chemicals. Expert tips on natural methods, DIY masks, and professional treatments for straight hair.',
        'category' => 'Hair Styling',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-straighten-hair-naturally-at-home.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Style Short Hair — Easy Tips & Ideas for Every Occasion',
        'desc'     => 'Discover how to style short hair with easy tips, trendy ideas, and expert advice. From casual to formal, learn the best short hair styling techniques.',
        'category' => 'Hair Styling',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-style-short-hair-tips-ideas.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Take Care of Hair: Complete Hair Care Guide',
        'desc'     => 'Learn how to take care of hair properly with expert tips on daily routines, nutrition, washing, and treatments. Your complete guide to healthy, beautiful hair.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-take-care-of-hair.png',
        'url'      => 'blog/how-to-take-care-of-hair-complete-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Use Hair Conditioner: Complete Guide for All Hair Types',
        'desc'     => 'Learn how to use hair conditioner correctly for soft, shiny, and healthy hair. Step-by-step guide on application techniques, timing, and choosing the right conditioner.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-use-hair-conditioner.png',
        'url'      => 'blog/how-to-use-hair-conditioner-complete-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Use Hair Mask: Benefits, Tips & Step-by-Step Guide',
        'desc'     => 'Learn how to use a hair mask correctly for deep conditioning and repair. Discover the benefits of hair masks, how often to use them, and tips for every hair type.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-use-hair-mask.png',
        'url'      => 'blog/how-to-use-hair-mask-benefits-tips.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Use Hair Serum: Complete Guide for Shiny, Frizz-Free Hair',
        'desc'     => 'Learn how to use hair serum correctly for smooth, shiny, and frizz-free hair. Step-by-step guide on application, choosing the right serum, and common mistakes to avoid.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-use-hair-serum.png',
        'url'      => 'blog/how-to-use-hair-serum-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Wash Hair Properly: Step-by-Step Guide',
        'desc'     => 'Learn the correct way to wash your hair with our step-by-step guide. Discover proper shampooing technique, water temperature tips, and common washing mistakes to avoid.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-wash-hair-properly.png',
        'url'      => 'blog/how-to-wash-hair-properly-step-by-step.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Botox Treatment Good for Hair? Expert Review & Honest Analysis',
        'desc'     => 'Is botox treatment actually good for your hair? Read our expert analysis of hair botox benefits, potential risks, who should get it, and realistic expectations.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/is-botox-treatment-good-for-hair-expert-review.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Conditioner Good for Hair? Benefits, Myths & Expert Facts',
        'desc'     => 'Is conditioner good for hair or does it cause damage? Learn the truth about hair conditioner benefits, who should use it, and common myths debunked by experts.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/is-conditioner-good-for-hair.png',
        'url'      => 'blog/is-conditioner-good-for-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Hair Spa Good for Hair? Benefits, Side Effects & Expert Opinion',
        'desc'     => 'Find out if hair spa is actually good for your hair. Learn about the proven benefits, potential side effects, and expert recommendations for hair spa treatments.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/is-hair-spa-good-for-hair-benefits-explained.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Hair Transplant Permanent? Longevity, Results & What to Expect',
        'desc'     => 'Is hair transplant really permanent? Learn how long hair transplant results last, what affects longevity, and how to maintain your transplanted hair for life.',
        'category' => 'Hair Transplant',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/is-hair-transplant-permanent-longevity-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Hair Transplant Safe? Risks, Facts & What to Expect',
        'desc'     => 'Is hair transplant surgery safe? Learn about the safety of modern hair transplant procedures, potential risks, success rates, and how to ensure a safe experience.',
        'category' => 'Hair Transplant',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/is-hair-transplant-safe-risks-and-facts.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Keratin Treatment Good for Hair? Pros, Cons & Expert Advice',
        'desc'     => 'Is keratin treatment worth it? Discover the pros and cons of keratin hair treatment, how it works, who should get it, and expert advice on maintaining results.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/is-keratin-treatment-good-for-hair-pros-cons.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Sodium Laureth Sulfate Good for Hair? SLES Facts Explained',
        'desc'     => 'Is Sodium Laureth Sulfate (SLES) good or bad for your hair? Learn what SLES does, how it affects different hair types, and whether you should avoid sulfate shampoos.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/is-sodium-laureth-sulfate-good-for-hair.png',
        'url'      => 'blog/is-sodium-laureth-sulfate-good-for-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What Is Botox Hair Treatment? Process, Benefits & Results',
        'desc'     => 'Learn everything about botox hair treatment - how it works, its benefits for damaged hair, the procedure, expected results, and whether it is right for your hair type.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/what-is-botox-hair-treatment-complete-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What Is Hair Spa? Complete Guide to Benefits, Process & Results',
        'desc'     => 'Discover what a hair spa is, how it works, its benefits for hair health, and why it is one of the most popular salon treatments for damaged and dry hair.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/what-is-hair-spa-complete-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What to Eat for Hair Growth: Best Foods for Thicker Hair',
        'desc'     => 'Discover the best foods to eat for hair growth. From protein-rich eggs to iron-packed spinach, learn how your diet can promote stronger, thicker, and healthier hair naturally.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/what-to-eat-hair-growth-featured.png',
        'url'      => 'blog/what-to-eat-for-hair-growth.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What to Eat to Prevent Hair Loss: Diet Plan & Expert Tips',
        'desc'     => 'Learn what to eat to prevent hair loss naturally. Discover the best anti-hair-loss foods, essential nutrients, and a diet plan that keeps your hair strong and healthy.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/prevent-hair-loss-diet-featured.png',
        'url'      => 'blog/what-to-eat-to-prevent-hair-loss.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What to Eat to Reduce Hair Fall: Foods That Strengthen Hair',
        'desc'     => 'Find out what to eat to reduce hair fall naturally. This expert guide covers the best hair-strengthening foods, essential nutrients, and dietary tips to stop excessive shedding.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/reduce-hair-fall-diet-featured.png',
        'url'      => 'blog/what-to-eat-to-reduce-hair-fall.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'What to Eat to Stop Hair Fall Immediately: Emergency Diet Tips',
        'desc'     => 'Looking for foods that can stop hair fall quickly? Discover the best emergency diet tips, nutrient-dense foods, and rapid dietary changes to control excessive hair shedding fast.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/stop-hair-fall-immediately-food-featured.png',
        'url'      => 'blog/what-to-eat-to-stop-hair-fall-immediately.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Which Conditioner Is Best for Hair? Expert Guide by Hair Type',
        'desc'     => 'Find out which conditioner is best for your hair type. Expert recommendations for dry, oily, thin, thick, curly, and color-treated hair with ingredient breakdowns.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/which-conditioner-is-best-for-hair.png',
        'url'      => 'blog/which-conditioner-is-best-for-hair.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Which Fruit Is Good for Hair Growth? Top 15 Fruits for Healthy Hair',
        'desc'     => 'Discover which fruits are best for hair growth. From vitamin C-rich berries to iron-boosting pomegranates, learn how fruits can naturally promote thicker, stronger hair.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/fruits-for-hair-growth-featured.png',
        'url'      => 'blog/which-fruit-is-good-for-hair-growth.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Which Vitamin Is Essential for Hair Growth? Complete Guide',
        'desc'     => 'Find out which vitamins are essential for hair growth. From biotin to vitamin D, learn how each vitamin supports healthy hair and where to get them from food and supplements.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/essential-vitamins-hair-growth-featured.png',
        'url'      => 'blog/which-vitamin-is-essential-for-hair-growth.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Which Vitamin Is Good for Hair Fall Control? Expert Guide',
        'desc'     => 'Learn which vitamins help control hair fall effectively. Discover the best vitamins for reducing hair shedding, their food sources, dosages, and when to consider supplements.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/vitamins-hair-fall-control-featured.png',
        'url'      => 'blog/which-vitamin-is-good-for-hair-fall-control.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Henna Good for Hair? Benefits, Risks & Expert Guide',
        'desc'     => 'Is henna good for hair? Discover the benefits and risks of using henna, natural vs chemical henna, application tips, and who should avoid it.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/is-henna-good-for-hair.png',
        'url'      => 'blog/is-henna-good-for-hair-benefits-risks.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Does Hair Dryer Damage Hair? Science-Backed Truth',
        'desc'     => 'Does hair dryer damage hair? Discover the science behind heat damage, how blow drying affects different hair types, and expert tips to protect your hair.',
        'category' => 'Hair Science',
        'image'    => 'images/blog/does-hair-dryer-damage-hair.png',
        'url'      => 'blog/does-hair-dryer-damage-hair-truth.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Is Hair Dryer Good for Hair? Expert Facts & Tips',
        'desc'     => 'Is hair dryer good for hair or does it cause damage? Learn the truth about blow drying, how to minimize heat damage, and expert tips for safe drying.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/is-hair-dryer-good-for-hair.png',
        'url'      => 'blog/is-hair-dryer-good-for-hair-facts.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Remove Hair Dye from Skin: Safe & Easy Methods',
        'desc'     => 'Learn how to remove hair dye from skin safely using home remedies and professional tips. Easy methods to get rid of dye stains from forehead, neck, and hands.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-remove-hair-dye-from-skin.png',
        'url'      => 'blog/how-to-remove-hair-dye-from-skin.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How Many Strands of Hair Does the Average Head Contain?',
        'desc'     => 'Find out how many strands of hair the average head contains. Learn about hair strand count, daily shedding, growth rates, and what affects your total hair volume.',
        'category' => 'Hair Science',
        'image'    => 'images/blog/how-many-strands-of-hair.png',
        'url'      => 'blog/how-many-strands-of-hair-on-average-head.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How Many Hairs on a Human Head? Facts & Science',
        'desc'     => 'Discover how many hairs are on a human head. Learn about average hair count by color, factors affecting hair density, and how many strands you lose daily.',
        'category' => 'Hair Science',
        'image'    => 'images/blog/how-many-hairs-on-human-head.png',
        'url'      => 'blog/how-many-hairs-on-human-head.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Know Your Hair Type: Complete Classification Guide',
        'desc'     => 'Learn how to know your hair type with our complete guide covering straight, wavy, curly, and coily hair. Discover your texture, density, and porosity.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-know-your-hair-type.png',
        'url'      => 'blog/how-to-know-your-hair-type-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Check Hair Porosity: Simple Tests & Care Tips',
        'desc'     => 'Learn how to check hair porosity with simple at-home tests. Understand low, medium, and high porosity hair and discover the best care routine for your type.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/how-to-check-hair-porosity.png',
        'url'      => 'blog/how-to-check-hair-porosity-guide.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'Can White Hair Turn Black Again? Truth Revealed',
        'desc'     => 'Kya safed baal wapas kale ho sakte hain? Scientific truth about reversing grey hair — kab possible hai aur kab nahi. Expert guide by DenceSpot.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_10.png',
        'url'      => 'blog/can-white-hair-turn-black-again.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'Which Vitamin Deficiency Causes White Hair?',
        'desc'     => 'Konsi vitamin ki kami se baal safed hote hain? B12, D3, iron, copper, zinc — complete guide on deficiencies aur premature greying.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_9.png',
        'url'      => 'blog/which-vitamin-deficiency-causes-white-hair.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'Why Does Hair Become White? Causes Explained',
        'desc'     => 'Baal safed kyun hote hain? Complete scientific explanation — genetics, stress, vitamin deficiency aur more. DenceSpot Clinic expert guide.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_8.png',
        'url'      => 'blog/why-hair-become-white.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Make Hair Black Naturally at Home',
        'desc'     => 'Baal kale karne ke gharelu nuskhe — DIY hair masks, homemade oils, henna+indigo process aur diet tips. DenceSpot Clinic expert guide.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_7.png',
        'url'      => 'blog/how-to-make-hair-black-naturally.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Turn White Hair Black Naturally',
        'desc'     => 'Safed baal kale karne ke natural tarike — Ayurvedic remedies, kitchen solutions, superfoods aur clinical treatments. No dye needed.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_6.png',
        'url'      => 'blog/how-to-turn-hair-black-naturally.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Prevent White Hair from Spreading',
        'desc'     => 'Safed baal failne se kaise roke? Step-by-step prevention plan with diet, natural remedies aur clinical treatments. DenceSpot expert guide.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_5.png',
        'url'      => 'blog/how-to-prevent-white-hair-from-spreading.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Get Rid of White Hair Permanently',
        'desc'     => 'Safed baalon se chutkara kaise paayen? Natural remedies, clinical treatments aur expert tips. DenceSpot Clinic Gurgaon complete guide.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_4.png',
        'url'      => 'blog/how-to-get-rid-of-white-hair.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Stop Grey Hair Naturally',
        'desc'     => 'Grey hair ko naturally kaise roke? Home remedies, diet plan aur advanced treatments. Complete guide by DenceSpot Clinic Gurgaon.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_3.png',
        'url'      => 'blog/how-to-stop-grey-hair.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Stop White Hair from Growing',
        'desc'     => 'Safed baal kaise roke? Complete guide with natural remedies, diet tips aur clinical treatments. Premature greying ko rokein.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_2.png',
        'url'      => 'blog/how-to-stop-white-hair.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How to Reduce White Hair Naturally',
        'desc'     => 'Safed baal kam karne ke proven tarike — home remedies, diet changes aur clinical treatments. Expert tips by DenceSpot Clinic Gurgaon.',
        'category' => 'White Hair',
        'image'    => 'assets/images/ht_gallery_extra_1.png',
        'url'      => 'blog/how-to-reduce-white-hair.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'Does Whey Protein Cause Hair Loss? Gym Guide',
        'desc'     => 'Kya whey protein se baal girte hain? Gym jaane walon ke liye complete guide — safe supplements, risky ones, aur hair-friendly nutrition.',
        'category' => 'Hair Loss Myths',
        'image'    => 'assets/images/ht_gallery_extra_7.png',
        'url'      => 'blog/does-whey-protein-cause-hair-loss-gym-guide.php',
        'date'     => '2026-03-30',
    ],
    [
        'title'    => 'Does Masturbation Cause Hair Loss? Medical Facts',
        'desc'     => 'Kya hastmaithun se baal jhad-te hain? Scientific evidence aur medical facts se jaaniye sach. Expert doctors ne is myth ko debunk kiya.',
        'category' => 'Hair Loss Myths',
        'image'    => 'assets/images/ht_gallery_extra_6.png',
        'url'      => 'blog/does-masturbation-cause-hair-loss-medical-facts.php',
        'date'     => '2026-03-29',
    ],
    [
        'title'    => 'Does Caffeine Cause Hair Loss? Myth or Fact',
        'desc'     => 'Kya chai ya coffee se baal girte hain? Surprising truth — caffeine actually hair growth mein help kar sakti hai.',
        'category' => 'Hair Loss Myths',
        'image'    => 'assets/images/ht_gallery_extra_5.png',
        'url'      => 'blog/does-caffeine-cause-hair-loss-myth-or-fact.php',
        'date'     => '2026-03-28',
    ],
    [
        'title'    => 'Does Smoking Cause Hair Loss? Science Explained',
        'desc'     => 'Kya smoking se baal jhad sakte hain? Scientific evidence, studies aur recovery timeline. Expert guide by DenceSpot Clinic.',
        'category' => 'Hair Loss Causes',
        'image'    => 'assets/images/ht_gallery_extra_4.png',
        'url'      => 'blog/does-smoking-cause-hair-loss-science-explained.php',
        'date'     => '2026-03-27',
    ],
    [
        'title'    => 'Can Dandruff Cause Hair Fall? Truth Explained',
        'desc'     => 'Kya dandruff se sach mein baal jhad sakte hain? Jaaniye dandruff aur hair fall ka real connection aur treatment options.',
        'category' => 'Scalp Health',
        'image'    => 'assets/images/dandruff_indian_ba_1773724686736.png',
        'url'      => 'blog/can-dandruff-cause-hair-fall-truth-explained.php',
        'date'     => '2026-03-26',
    ],
    [
        'title'    => 'How to Control Hair Fall for Women — Expert Guide',
        'desc'     => 'Women ke hair fall ko kaise rokein? PCOS, thyroid, pregnancy aur menopause se hone wale baal girne ka complete expert guide.',
        'category' => "Women's Hair Care",
        'image'    => 'assets/images/skin_treatment_indian_ba_1773724789009.png',
        'url'      => 'blog/how-to-control-hair-fall-for-women-expert-guide.php',
        'date'     => '2026-03-25',
    ],
    [
        'title'    => 'How to Stop Hair Fall After COVID: Recovery Guide',
        'desc'     => 'COVID ke baad baal bahut jhadte hain? Post-COVID hair fall ka complete recovery guide — causes, treatment aur prevention.',
        'category' => 'Hair Fall',
        'image'    => 'images/blog/scalp-massage.png',
        'url'      => 'blog/how-to-stop-hair-fall-after-covid-recovery-guide.php',
        'date'     => '2026-03-24',
    ],
    [
        'title'    => 'How to Stop Hair Loss and Regrow Hair Naturally',
        'desc'     => 'Baal girna kaise roke aur naturally regrow kaise karein? Complete guide with proven methods and clinical treatments.',
        'category' => 'Hair Regrowth',
        'image'    => 'images/blog/hair-growth-lifestyle.png',
        'url'      => 'blog/how-to-stop-hair-loss-and-regrow-hair-naturally.php',
        'date'     => '2026-03-23',
    ],
    [
        'title'    => 'How to Prevent Hair Loss Before It Starts',
        'desc'     => 'Hair loss ko shuru hone se pehle kaise rokein? Early prevention tips, diet, lifestyle aur clinical treatments guide.',
        'category' => 'Hair Prevention',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-prevent-hair-loss-before-it-starts.php',
        'date'     => '2026-03-22',
    ],
    [
        'title'    => 'How to Reduce Hair Fall Naturally: Home Remedies',
        'desc'     => 'Ghar baithe baal jharna kaise kam karein? Proven natural remedies — oil massage, diet, herbs aur scalp care tips.',
        'category' => 'Natural Remedies',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-reduce-hair-fall-naturally-home-remedies.php',
        'date'     => '2026-03-21',
    ],
    [
        'title'    => 'How to Stop Hair Fall Immediately: Emergency Tips',
        'desc'     => 'Baal turant girna kaise rokein? Emergency hair fall tips jo aaj se kaam karein — diet, care routine aur quick fixes.',
        'category' => 'Hair Fall',
        'image'    => 'images/blog/hair-growth-tips-featured.png',
        'url'      => 'blog/how-to-stop-hair-fall-immediately-emergency-tips.php',
        'date'     => '2026-03-20',
    ],
    [
        'title'    => 'How to Control Hair Fall: Complete Guide',
        'desc'     => 'Hair fall control kaise karein? Expert guide on causes, home remedies aur clinical treatments like PRP & microneedling.',
        'category' => 'Hair Fall',
        'image'    => 'images/blog/hair-fall-prevention-featured.png',
        'url'      => 'blog/how-to-control-hair-fall-complete-guide.php',
        'date'     => '2026-03-19',
    ],
    [
        'title'    => 'How Can I Make My Hair Thicker? Expert Dermatologist Answers',
        'desc'     => 'Expert dermatologist answers the most common questions about making thin hair thicker — from home remedies to clinical treatments.',
        'category' => 'Hair Thickness',
        'image'    => 'assets/images/hair_led_indian_ba_1773724717444.png',
        'url'      => 'blog/how-can-i-make-my-hair-thicker-expert-answers.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Make Hair Thicker and Stronger: Complete Guide',
        'desc'     => 'Learn how to make thin, weak hair thicker and stronger with nutrition, clinical treatments, and the right daily routine.',
        'category' => 'Hair Thickness',
        'image'    => 'assets/images/hair_microneedling_indian_ba_1773724737453.png',
        'url'      => 'blog/how-to-make-hair-thicker-and-stronger.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Thicken Hair Naturally: Proven Home Remedies',
        'desc'     => 'Discover proven natural remedies to thicken thin hair at home — oils, masks, scalp massage, and diet tips from experts.',
        'category' => 'Hair Thickness',
        'image'    => 'images/blog/rosemary-oil-preparation.png',
        'url'      => 'blog/how-to-thicken-hair-naturally-home-remedies.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Get Thicker Hair Naturally and Clinically',
        'desc'     => 'A science-backed guide to getting thicker hair using natural remedies and clinical treatments like PRP and microneedling.',
        'category' => 'Hair Thickness',
        'image'    => 'images/blog/hair-vitamins-supplements.png',
        'url'      => 'blog/how-to-get-thicker-hair-naturally-and-clinically.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Increase Hair Volume: Tips and Treatments',
        'desc'     => 'Expert tips to increase hair volume — from styling tricks to clinical treatments for fuller, voluminous hair.',
        'category' => 'Hair Thickness',
        'image'    => 'images/blog/hair-serum-application.png',
        'url'      => 'blog/how-to-increase-hair-volume-tips-treatments.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Increase Hair Thickness: Dermatologist Guide',
        'desc'     => 'A dermatologist-approved guide to increasing hair thickness through diet, treatments, and lifestyle changes.',
        'category' => 'Hair Thickness',
        'image'    => 'images/blog/hair-thickness-density-featured.png',
        'url'      => 'blog/how-to-increase-hair-thickness-dermatologist-guide.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Increase Hair Density: Proven Methods',
        'desc'     => 'Proven methods to increase hair density — from PRP and microneedling to diet changes and high-density hair transplant.',
        'category' => 'Hair Density',
        'image'    => 'images/blog/hair-thickness-density-featured.png',
        'url'      => 'blog/how-to-increase-hair-density-proven-methods.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Grow Hair on Forehead: Receding Hairline Solutions',
        'desc'     => 'Complete guide to regrowing hair on the forehead — from minoxidil and PRP to hairline restoration surgery.',
        'category' => 'Hair Growth',
        'image'    => 'assets/images/ht_gallery_extra_3.png',
        'url'      => 'blog/how-to-grow-hair-on-forehead-receding-hairline-solutions.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Grow Natural Hair Without Chemicals',
        'desc'     => 'Learn how to grow healthy natural hair without harsh chemicals — oils, diet, scalp care, and when clinical help is needed.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-oil-massage.png',
        'url'      => 'blog/how-to-grow-natural-hair-without-chemicals.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Grow Long Hair for Men: Complete Guide',
        'desc'     => 'The ultimate guide for Indian men who want to grow long, healthy hair — grooming, diet, and clinical treatments.',
        'category' => 'Hair Growth',
        'image'    => 'assets/images/ht_gallery_extra_2.png',
        'url'      => 'blog/how-to-grow-long-hair-for-men-complete-guide.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Grow Hair in 1 Week: Reality Check',
        'desc'     => 'Can you really grow hair in 1 week? A dermatologist separates myths from reality and shares what actually works.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/scalp-massage.png',
        'url'      => 'blog/how-to-grow-hair-in-1-week-reality-check.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'How to Grow Hair Faster: Tips That Actually Work',
        'desc'     => 'Science-backed tips to grow hair faster — diet, scalp care, clinical treatments, and myths debunked by experts.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-growth-tips-featured.png',
        'url'      => 'blog/how-to-grow-hair-faster-tips-that-actually-work.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant Cost vs Results: What Every Patient Should Realistically Expect',
        'desc'     => 'Understand how hair transplant pricing works, what cheap clinics cut corners on, and what realistic density results look like after surgery.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht-success-2.png',
        'url'      => 'blog/hair-transplant-cost-vs-results-patient-expectations.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant Recovery Timeline: What Patients Feel Week by Week',
        'desc'     => 'A detailed week-by-week recovery guide after hair transplant — from day-1 swelling to month-12 final results.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht-success-1.png',
        'url'      => 'blog/hair-transplant-recovery-timeline-week-by-week.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'What a Patient Experiences During Hair Transplant Surgery: Step-by-Step',
        'desc'     => 'A complete step-by-step walkthrough of what happens on hair transplant day — from arrival to going home.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/tech-procedure.png',
        'url'      => 'blog/hair-transplant-surgery-step-by-step-patient-experience.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Why Some Patients Don\'t Get Desired Results After Hair Transplant',
        'desc'     => 'Explore the real reasons behind poor hair transplant outcomes — from clinic selection to post-op care — and how to avoid them.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/indian-ht-result-2.png',
        'url'      => 'blog/why-patients-dont-get-desired-results-hair-transplant.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant Gone Wrong? Common Patient Mistakes to Avoid',
        'desc'     => 'Discover the most common mistakes patients make before and after hair transplant surgery — and how to protect your results.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_success_real_1.png',
        'url'      => 'blog/hair-transplant-gone-wrong-common-patient-mistakes.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'What Happens If You Don\'t Have Enough Donor Hair? Patient Options',
        'desc'     => 'Learn what options exist when donor hair supply is limited — from body hair transplant to SMP and PRP conditioning.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_crown_real.png',
        'url'      => 'blog/not-enough-donor-hair-transplant-options.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Can Patients with Diabetes or BP Undergo Hair Transplant? Expert Insights',
        'desc'     => 'Find out how diabetes and high blood pressure affect hair transplant eligibility, HbA1c thresholds, and pre-op clearance.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_hairline_real.png',
        'url'      => 'blog/hair-transplant-diabetes-blood-pressure-patients.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Transplant for Different Age Groups: What Patients Should Know',
        'desc'     => 'How age affects hair transplant candidacy, results, and planning — from under 25 to 50+ patients.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_gallery_extra_1.png',
        'url'      => 'blog/hair-transplant-different-age-groups-what-to-know.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Who Is an Ideal Candidate for Hair Transplant? Age, Hair Loss & Health',
        'desc'     => 'A detailed look at what makes someone an ideal hair transplant candidate — donor density, Norwood scale, age, and health factors.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/indian-ht-result-1.png',
        'url'      => 'blog/ideal-candidate-hair-transplant-age-hair-loss-health.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Is Hair Transplant Right for You? A Complete Patient Eligibility Guide',
        'desc'     => 'Not everyone is a candidate. This guide covers all eligibility criteria for hair transplant — medical, physical, and psychological.',
        'category' => 'Hair Transplant',
        'image'    => 'assets/images/ht_success_real.png',
        'url'      => 'blog/is-hair-transplant-right-for-you-eligibility-guide.php',
        'date'     => '2026-03-18',
    ],
    [
        'title'    => 'Hair Fall & Hair Loss Prevention: The Ultimate Guide',
        'desc'     => 'Discover the most effective strategies to stop hair fall and maintain thick, healthy hair naturally.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/hair-fall-prevention-featured.png',
        'url'      => 'blog/hair-fall-and-hair-loss-prevention.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Hair Growth Tips & Methods: How to Grow Hair Faster',
        'desc'     => 'The best hair growth tips and methods to accelerate hair growth naturally through scalp health, diet, and clinical treatments.',
        'category' => 'Hair Growth',
        'image'    => 'images/blog/hair-growth-tips-featured.png',
        'url'      => 'blog/hair-growth-tips-and-methods.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Best Oils for Hair Growth: A Comprehensive Guide',
        'desc'     => 'From Rosemary to Castor oil — explore the best natural oils for thicker, longer hair and how to use them effectively.',
        'category' => 'Hair Care',
        'image'    => 'images/blog/best-hair-oils-featured.png',
        'url'      => 'blog/best-hair-oils-for-growth-benefits.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Hair Thickness & Hair Density Improvement: The Complete Guide',
        'desc'     => 'Learn how to increase hair thickness and improve hair density naturally with the best tips, treatments, and products.',
        'category' => 'Hair Volume',
        'image'    => 'images/blog/hair-thickness-density-featured.png',
        'url'      => 'blog/hair-thickness-and-hair-density-improvement.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Vitamins & Nutrition for Healthy Hair: The Ultimate Diet Guide',
        'desc'     => 'Which vitamins and nutrients are essential for healthy hair? Discover the best foods and supplements to stop hair loss.',
        'category' => 'Nutrition',
        'image'    => 'images/blog/vitamins-for-hair-featured.png',
        'url'      => 'blog/vitamins-nutrition-healthy-hair.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Dandruff & Scalp Problems: Causes and Effective Treatments',
        'desc'     => 'Struggling with flakes or an itchy scalp? Learn about causes of dandruff and the most effective clinical and natural treatments.',
        'category' => 'Scalp Health',
        'image'    => 'images/blog/dandruff-scalp-problems-featured.png',
        'url'      => 'blog/dandruff-scalp-problems-treatment.php',
        'date'     => '2026-03-11',
    ],
    [
        'title'    => 'Understanding Hair Transplant: Myths vs Facts',
        'desc'     => 'We bust common myths and highlight essential facts you need to know before booking your hair transplant procedure.',
        'category' => 'Hair Care',
        'image'    => 'images/hair-transplant-original.jpg',
        'url'      => 'blog/understanding-hair-transplant-myths-vs-facts.php',
        'date'     => '2026-02-25',
    ],
    [
        'title'    => 'Benefits of HydraFacial: How It Transforms Your Skin',
        'desc'     => 'How HydraFacial deep-cleans, exfoliates, and hydrates for an instant radiant glow with zero downtime.',
        'category' => 'Skin Care',
        'image'    => 'images/hydrafacial.jpg',
        'url'      => 'blog/benefits-of-hydrafacial-how-it-transforms-your-skin.php',
        'date'     => '2026-02-18',
    ],
    [
        'title'    => 'Everything You Need to Know About Botox and Fillers',
        'desc'     => 'The complete guide to anti-ageing injectables — differences between Botox and dermal fillers and how to choose the best treatment.',
        'category' => 'Anti-Ageing',
        'image'    => 'images/botox.jpg',
        'url'      => 'blog/everything-you-need-to-know-about-botox-and-fillers.php',
        'date'     => '2026-02-12',
    ],
    [
        'title'    => 'Is Laser Hair Removal Permanent? Expert Perspective',
        'desc'     => 'Our experts explain how laser hair removal technology works, what results to expect, and why it\'s the best choice for smooth skin.',
        'category' => 'Laser',
        'image'    => 'images/laser-hair-removel-gurgaon.jpg',
        'url'      => 'blog/is-laser-hair-removal-permanent-expert-perspective.php',
        'date'     => '2026-02-05',
    ],
    [
        'title'    => 'PRP Hair Treatment: The Natural Way to Regrow Your Hair',
        'desc'     => 'How Platelet-Rich Plasma therapy uses your own blood to stimulate hair growth and thickening — naturally.',
        'category' => 'Hair Care',
        'image'    => 'images/service-hair.png',
        'url'      => 'blog/prp-hair-treatment-natural-way-to-regrow-hair.php',
        'date'     => '2026-01-21',
    ],
    [
        'title'    => 'Chemical Peels: Finding the Right Depth for Your Skin Type',
        'desc'     => 'A complete guide to chemical peels — from light to deep — and which treatment is best for your specific skin concerns.',
        'category' => 'Skin Care',
        'image'    => 'images/service-skin.png',
        'url'      => 'blog/chemical-peels-finding-the-right-depth-for-your-skin-type.php',
        'date'     => '2026-01-08',
    ],
];
